#!/usr/bin/env ruby

PROJECT = Dir.open(Dir.pwd)
git = proc { |f| f == ".git" }.freeze
rspec = proc { |f| f == "spec" || f == ".rspec" }.freeze
rubocop = proc { |f| f == ".rubocop.yml" }.freeze
PROJECT_PATH = PROJECT.path.freeze

def hide_console_output
  $stdout = StringIO.new
  yield
ensure
  $stdout = STDOUT
end

puts "~ Running Plain Old Ruby Object Script ~".center(50, " ")
# Check for Rspec
if PROJECT.detect(&rspec)
  puts "RSpec already installed."
else
  `rspec --init`
  puts "Added Rspec v.#{`rspec --version`}"
end

# Check for Rubocop
if PROJECT.detect(&rubocop)
  puts "Rubocop already configured."
else
  `cp ~/scripts/rbporo/.rubocop.yml #{PROJECT_PATH}`
  puts "Added Rubocop v.#{`rubocop --version`}"
end

# Create Git Repository unless already created.
unless PROJECT.detect(&git)
  hide_console_output do
    `git init`
    `git add .`
    `git commit -m "Initial Commit"`
  end
end

# For Testing Only, to elimate repetition.
def remove_rspec
  `rm -rf spec`
  `rm .rspec`
end

def remove_rubocop
  `rm .rubocop.yml`
end

# remove_rspec
# remove_rubocop
